---
name: Spark-Form
version: 0.1
author:
  - 'James Laver <sprintf qw(%s@%s.%s cpan jameslaver com)>'
abstract: A simple yet powerful forms validation system that promotes reuse.
license: perl
resources:
  license: ~
requires:
  HTML::Tiny: 0
  List::MoreUtils: 0
  Module::Pluggable: 0
  Moose: 0
  MooseX::AttributeHelpers: 0
build_requires:
  Test::More: 0
provides:
  Spark::Form:
    file: lib/Spark/Form.pm
    version: 0.1
  Spark::Form::Field:
    file: lib/Spark/Form/Field.pm
  Spark::Form::Field::Role::Printable:
    file: lib/Spark/Form/Field/Role/Printable.pm
  Spark::Form::Field::Role::Printable::HTML:
    file: lib/Spark/Form/Field/Role/Printable/HTML.pm
  Spark::Form::Field::Role::Printable::XHTML:
    file: lib/Spark/Form/Field/Role/Printable/XHTML.pm
  Spark::Form::Field::Role::Validateable:
    file: lib/Spark/Form/Field/Role/Validateable.pm
  Spark::Form::Printer:
    file: lib/Spark/Form/Printer.pm
  Spark::Form::Printer::HTML:
    file: lib/Spark/Form/Printer/HTML.pm
  Spark::Form::Printer::XHTML:
    file: lib/Spark/Form/Printer/XHTML.pm
  Spark::Form::Source:
    file: lib/Spark/Form/Source.pm
generated_by: Module::Build version 0.32
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
